const app = require('./App');

const port = process.env.PORT

app.listen(port, () => {
    console.log('Server is up on port ' + port)
})

// const addBooks = (books) => {
//     for (const book of books) {
//         axios({
//             method: 'post',
//             url: 'http://localhost:3000/books',
//             data: book
//         });
//     }

// }

// const booksData = [{
//     imgSrc: 'https://images-na.ssl-images-amazon.com/images/I/41+lolL22gL._SX314_BO1,204,203,200_.jpg',
//     title: 'Sapiens - A Brief History of Humankind',
//     shortTitle: 'Sapiens',
//     author: 'Yuval Noah Harari',
//     genre: 'Non-Fiction',
//     price: 19.99,
//     discount: 0,
//     isTopSeller: true,
//     isNewArrival: false
// }, {
//     imgSrc: 'https://images-na.ssl-images-amazon.com/images/I/81hMjlT14ML.jpg',
//     title: 'Homo Deus - A Brief History of Tomorrow',
//     shortTitle: 'Homo Deus',
//     author: 'Yuval Noah Harari',
//     genre: 'Non-Fiction',
//     price: 19.99,
//     discount: 0,
//     isTopSeller: false,
//     isNewArrival: true
// }, {
//     imgSrc: 'https://images-na.ssl-images-amazon.com/images/I/81iqZ2HHD-L.jpg',
//     title: 'Harry Potter and the Sorcerer\'s Stone',
//     shortTitle: 'Harry Potter 1',
//     author: 'J.K Rowling',
//     genre: 'Fantasy',
//     price: 34.99,
//     discount: 35,
//     isTopSeller: true,
//     isNewArrival: false
// }, {
//     imgSrc: 'https://hpmedia.bloomsbury.com/rep/s/9781408855904_309575.jpeg',
//     title: 'Harry Potter and the Chamber of Secrets',
//     shortTitle: 'Harry Potter 2',
//     author: 'J.K Rowling',
//     genre: 'Fantasy',
//     price: 44.99,
//     discount: 35,
//     isTopSeller: false,
//     isNewArrival: false
// }, {
//     imgSrc: 'https://images-na.ssl-images-amazon.com/images/I/91uix57X+jL.jpg',
//     title: 'Harry Potter and the Prisoner of Azkaban',
//     shortTitle: 'Harry Potter 3',
//     author: 'J.K Rowling',
//     genre: 'Fantasy',
//     price: 44.99,
//     discount: 30,
//     isTopSeller: false,
//     isNewArrival: false
// }, {
//     imgSrc: 'https://prodimage.images-bn.com/pimages/9780439139601_p0_v1_s550x406.jpg',
//     title: 'Harry Potter and the Goblet of Fire',
//     shortTitle: 'Harry Potter 4',
//     author: 'J.K Rowling',
//     genre: 'Fantasy',
//     price: 44.99,
//     discount: 25,
//     isTopSeller: false,
//     isNewArrival: false
// }, {
//     imgSrc: 'https://images-na.ssl-images-amazon.com/images/I/91TpLHDnuFL.jpg',
//     title: 'Harry Potter and the Order of the Phoenix',
//     shortTitle: 'Harry Potter 5',
//     author: 'J.K Rowling',
//     genre: 'Fantasy',
//     price: 44.99,
//     discount: 20,
//     isTopSeller: false,
//     isNewArrival: false
// }, {
//     imgSrc: 'http://prodimage.images-bn.com/pimages/9780439785969_p0_v3_s1200x630.jpg',
//     title: 'Harry Potter and the Half Blooded Prince',
//     shortTitle: 'Harry Potter 6',
//     author: 'J.K Rowling',
//     genre: 'Fantasy',
//     price: 44.99,
//     discount: 10,
//     isTopSeller: true,
//     isNewArrival: false
// }, {
//     imgSrc: 'https://images-na.ssl-images-amazon.com/images/I/71sH3vxziLL.jpg',
//     title: 'Harry Potter and the Deadly Hallows',
//     shortTitle: 'Harry Potter 7',
//     author: 'J.K Rowling',
//     genre: 'Fantasy',
//     price: 44.99,
//     discount: 0,
//     isTopSeller: true,
//     isNewArrival: true
// }, {
//     imgSrc: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1327945104l/249747.jpg',
//     title: 'Artemis Fowl',
//     shortTitle: 'Artemis Fowl',
//     author: 'Eoin Colfer',
//     genre: 'Fantasy',
//     price: 30.99,
//     discount: 20,
//     isTopSeller: false,
//     isNewArrival: true
// }, {
//     imgSrc: 'https://images-na.ssl-images-amazon.com/images/I/61v5CqYL2WL.jpg',
//     title: 'Predictably Irrational',
//     shortTitle: 'Predictably Irrational',
//     author: 'Dan Arieli',
//     genre: 'Non-Fiction',
//     price: 13.99,
//     discount: 0,
//     isTopSeller: false,
//     isNewArrival: false
// }, {
//     imgSrc: 'https://images-na.ssl-images-amazon.com/images/I/51ZOvw%2BoHFL._AC_SY400_.jpg',
//     title: 'I Am Zlatan - My story on and off the Field',
//     shortTitle: 'I Am Zlatan',
//     author: 'David Lagercrantz',
//     genre: 'Biography',
//     price: 25.99,
//     discount: 10,
//     isTopSeller: false,
//     isNewArrival: true
// }, {
//     imgSrc: 'https://images-na.ssl-images-amazon.com/images/I/81UhKOBDrCL.jpg',
//     title: 'The Girl with the Dragon Tattoo',
//     shortTitle: 'Girl with the Dragon Tattoo',
//     author: 'Stieg Larsson',
//     genre: 'Thriller',
//     price: 32.99,
//     discount: 15,
//     isTopSeller: true,
//     isNewArrival: false
// }, {
//     imgSrc: 'https://images-na.ssl-images-amazon.com/images/I/A12eoRmZtsL.jpg',
//     title: 'The Girl who Played with Fire',
//     shortTitle: 'Girl who Played with Fire',
//     author: 'Stieg Larsson',
//     genre: 'Thriller',
//     price: 32.99,
//     discount: 10,
//     isTopSeller: true,
//     isNewArrival: false
// }, {
//     imgSrc: 'https://images-na.ssl-images-amazon.com/images/I/814hdIxmkgL.jpg',
//     title: 'The Girl who Kicked the Hornet\'s Nest',
//     shortTitle: 'Girl who Kicked the Hornet\'s Nest',
//     author: 'Stieg Larsson',
//     genre: 'Thriller',
//     price: 32.99,
//     discount: 0,
//     isTopSeller: true,
//     isNewArrival: true
// }, {
//     imgSrc: 'https://images-na.ssl-images-amazon.com/images/I/A1TJNCSNPzL.jpg',
//     title: 'Guinnes World Records 2021',
//     shortTitle: 'Guinnes World Records',
//     author: 'Guinnes World Records',
//     genre: 'Non-Fiction',
//     price: 10.99,
//     discount: 0,
//     isTopSeller: false,
//     isNewArrival: true
// }, {
//     imgSrc: 'https://images-na.ssl-images-amazon.com/images/I/810BkqRP+iL.jpg',
//     title: 'Fifty Shades of Grey',
//     shortTitle: 'Fifty Shades of Grey',
//     author: 'E L James',
//     genre: 'Romance',
//     price: 47.99,
//     discount: 20,
//     isTopSeller: true,
//     isNewArrival: false,
// }, {
//     imgSrc: 'https://images.gr-assets.com/books/1436732693l/13496.jpg',
//     title: 'A Game of Thrones',
//     shortTitle: 'Game of Thrones',
//     author: 'George R. R. Martin',
//     genre: 'Fantasy',
//     price: 50.99,
//     discount: 10,
//     isTopSeller: true,
//     isNewArrival: false,
// }, {
//     imgSrc: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/dc/A_Song_of_Ice_and_Fire_book_collection_box_set_cover.jpg/220px-A_Song_of_Ice_and_Fire_book_collection_box_set_cover.jpg',
//     title: 'A Song of Ice and Fire',
//     shortTitle: 'Song of Ice and Fire',
//     author: 'George R. R. Martin',
//     genre: 'Fantasy',
//     price: 50.99,
//     discount: 15,
//     isTopSeller: true,
//     isNewArrival: false,
// }, {
//     imgSrc: 'https://images.gr-assets.com/books/1353029077l/100915.jpg',
//     title: 'The Lion, the Witch and the Wardrobe',
//     shortTitle: 'Narnia',
//     author: 'C. S. Lewis',
//     genre: 'Fantasy',
//     price: 15.99,
//     discount: 10,
//     isTopSeller: false,
//     isNewArrival: false,
// }, {
//     imgSrc: 'https://images-eu.bookshop.org/product-images/images/9780008376062.jpg',
//     title: 'Lord of the Rings - The Fellowship of the ring',
//     shortTitle: 'Lord of the Rings 1',
//     author: 'J. R. R. Tolkein',
//     genre: 'Advantures',
//     price: 29.99,
//     discount: 15,
//     isTopSeller: true,
//     isNewArrival: false,
// }, {
//     imgSrc: 'https://bokunosekai.files.wordpress.com/2010/11/the-two-towers.jpg',
//     title: 'Lord of the Rings - The Two Towers',
//     shortTitle: 'Lord of the Rings 2',
//     author: 'J. R. R. Tolkein',
//     genre: 'Advantures',
//     price: 29.99,
//     discount: 10,
//     isTopSeller: false,
//     isNewArrival: false,
// }, {
//     imgSrc: 'https://m.media-amazon.com/images/I/41KGl2FqeAL.jpg',
//     title: 'Lord of the Rings - The Return of the King',
//     shortTitle: 'Lord of the Rings 3',
//     author: 'J. R. R. Tolkein',
//     genre: 'Advantures',
//     price: 29.99,
//     discount: 0,
//     isTopSeller: true,
//     isNewArrival: false,
// }, {
//     imgSrc: 'https://images-na.ssl-images-amazon.com/images/I/61xCUSb1dHL.jpg',
//     title: 'The Silence of the Lambs',
//     shortTitle: 'Silence of the Lambs',
//     author: 'Thomas Harris',
//     genre: 'Thriller',
//     price: 38.99,
//     discount: 5,
//     isTopSeller: false,
//     isNewArrival: false,
// }, {
//     imgSrc: 'https://images-na.ssl-images-amazon.com/images/I/91Q5dCjc2KL.jpg',
//     title: 'The Da Vinci Code',
//     shortTitle: 'The Da Vinci Code',
//     author: 'Dan Brown',
//     genre: 'Thriller',
//     price: 49.99,
//     discount: 0,
//     isTopSeller: true,
//     isNewArrival: false,
// }, {
//     imgSrc: 'https://images-na.ssl-images-amazon.com/images/I/811LR22WdaL.jpg',
//     title: 'Shutter Island',
//     shortTitle: 'Shutter Island',
//     author: 'Dennis Lehane',
//     genre: 'Thriller',
//     price: 10.99,
//     discount: 0,
//     isTopSeller: false,
//     isNewArrival: false,
// }, {
//     imgSrc: 'https://images.gr-assets.com/books/1461620558l/1886.jpg',
//     title: 'Pride and Prejudice',
//     shortTitle: 'Pride and Prejudice',
//     author: 'Jane Austen',
//     genre: 'Romance',
//     price: 49.99,
//     discount: 15,
//     isTopSeller: true,
//     isNewArrival: false,
// }, {
//     imgSrc: 'https://images.gr-assets.com/books/1328025229l/18405.jpg',
//     title: 'Gone with the Wind',
//     shortTitle: 'Gone with the Wind',
//     author: 'Margaret Mitchell',
//     genre: 'Romance',
//     price: 34.99,
//     discount: 0,
//     isTopSeller: false,
//     isNewArrival: false,
// }, {
//     imgSrc: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1327903636l/21787.jpg',
//     title: 'The Princess Bride',
//     shortTitle: 'The Princess Bride',
//     author: 'William Goldman',
//     genre: 'Romance',
//     price: 22.99,
//     discount: 0,
//     isTopSeller: false,
//     isNewArrival: true,
// }, {
//     imgSrc: 'https://images.gr-assets.com/books/1388282444l/386162.jpg',
//     title: 'The Hitchhiker’s Guide to the Galaxy',
//     shortTitle: 'Hitchhiker’s Guide',
//     author: 'Douglas Adams',
//     genre: 'Sci-Fi',
//     price: 10.99,
//     discount: 0,
//     isTopSeller: false,
//     isNewArrival: true,
// }, {
//     imgSrc: 'https://images.gr-assets.com/books/1348990566l/5470.jpg',
//     title: 'George Orwell - 1984',
//     shortTitle: '1984',
//     author: 'George Orwell',
//     genre: 'Sci-Fi',
//     price: 14.99,
//     discount: 10,
//     isTopSeller: true,
//     isNewArrival: false,
// }, {
//     imgSrc: 'https://images.gr-assets.com/books/1424037542l/7613.jpg',
//     title: 'Animal Farm',
//     shortTitle: 'Animal Farm',
//     author: 'George Orwell',
//     genre: 'Sci-Fi',
//     price: 17.99,
//     discount: 15,
//     isTopSeller: false,
//     isNewArrival: true,
// }, {
//     imgSrc: 'https://images.gr-assets.com/books/1498057733l/38447.jpg',
//     title: ' The Handmaid’s Tale',
//     shortTitle: ' The Handmaid’s Tale',
//     author: 'Margaret Atwood',
//     genre: 'Sci-Fi',
//     price: 54.99,
//     discount: 5,
//     isTopSeller: false,
//     isNewArrival: true,
// }, {
//     imgSrc: 'https://images.gr-assets.com/books/1479863624l/1618.jpg',
//     title: ' The Curious Incident of the Dog in the Night-Time',
//     shortTitle: 'The Curious Incident',
//     author: 'Mark Haddon',
//     genre: 'Mystery',
//     price: 17.99,
//     discount: 0,
//     isTopSeller: false,
//     isNewArrival: true,
// }, {
//     imgSrc: 'https://images.gr-assets.com/books/1479863624l/1618.jpg',
//     title: 'Gone Girl',
//     shortTitle: 'Gone Girl',
//     author: 'Gillian Flynn',
//     genre: 'Mystery',
//     price: 19.99,
//     discount: 0,
//     isTopSeller: false,
//     isNewArrival: false,
// }, {
//     imgSrc: 'https://images.gr-assets.com/books/1318116526l/51496.jpg',
//     title: 'The Strange Case of Dr. Jekyll and Mr. Hyde',
//     shortTitle: 'Dr Jekyll and MR Hyde',
//     author: 'Robert Louis Stevenson',
//     genre: 'Mystery',
//     price: 14.99,
//     discount: 10,
//     isTopSeller: true,
//     isNewArrival: false,
// }, {
//     imgSrc: 'https://images.gr-assets.com/books/1318116526l/51496.jpg',
//     title: 'Eye of the Needle',
//     shortTitle: 'Eye of the Needle',
//     author: 'Ken Follett',
//     genre: 'Mystery',
//     price: 19.99,
//     discount: 5,
//     isTopSeller: false,
//     isNewArrival: true,
// }, {
//     imgSrc: 'https://i.pinimg.com/originals/78/7a/84/787a8480a420158ea92e4c36156d3cb8.jpg',
//     title: 'The Godfather',
//     shortTitle: 'The Godfather',
//     author: 'Mario Puzo',
//     genre: 'Mystery',
//     price: 36.99,
//     discount: 25,
//     isTopSeller: false,
//     isNewArrival: true,
// }, {
//     imgSrc: 'https://images.gr-assets.com/books/1353277730l/11588.jpg',
//     title: 'The Shining',
//     shortTitle: 'The Shining',
//     author: 'Stephen King',
//     genre: 'Horror',
//     price: 44.99,
//     discount: 15,
//     isTopSeller: true,
//     isNewArrival: false,
// }, {
//     imgSrc: 'https://images.gr-assets.com/books/1387151694l/17245.jpg',
//     title: 'Dracula',
//     shortTitle: 'Dracula',
//     author: 'Bram Stoker',
//     genre: 'Horror',
//     price: 15.99,
//     discount: 35,
//     isTopSeller: false,
//     isNewArrival: false,
// }, {
//     imgSrc: 'https://images.gr-assets.com/books/1334416842l/830502.jpg',
//     title: 'IT',
//     shortTitle: 'IT',
//     author: 'Stephen King',
//     genre: 'Horror',
//     price: 34.99,
//     discount: 15,
//     isTopSeller: true,
//     isNewArrival: false,
// }, {
//     imgSrc: 'https://images.gr-assets.com/books/1375168676l/179780.jpg',
//     title: ' The Exorcist',
//     shortTitle: 'The Exorcist',
//     author: 'William Peter Blatty',
//     genre: 'Horror',
//     price: 29.99,
//     discount: 15,
//     isTopSeller: false,
//     isNewArrival: false,
// }, {
//     imgSrc: 'https://images.gr-assets.com/books/1386328204l/8908.jpg',
//     title: 'World War Z: An Oral History of the Zombie War',
//     shortTitle: 'World War Z',
//     author: 'Max Brooks',
//     genre: 'Horror',
//     price: 24.99,
//     discount: 0,
//     isTopSeller: false,
//     isNewArrival: true,
// }, {
//     imgSrc: 'https://images.gr-assets.com/books/1302190430l/1132643.jpg',
//     title: 'The Phantom of the Opera',
//     shortTitle: 'Phantom of the Opera',
//     author: 'Gaston Leroux',
//     genre: 'Horror',
//     price: 34.99,
//     discount: 0,
//     isTopSeller: false,
//     isNewArrival: true,
// }, {
//     imgSrc: 'https://images-na.ssl-images-amazon.com/images/I/81h2gWPTYJL.jpg',
//     title: 'Becoming',
//     shortTitle: 'Becoming',
//     author: 'Michelle Obama',
//     genre: 'Non-Fiction',
//     price: 54.99,
//     discount: 0,
//     isTopSeller: true,
//     isNewArrival: true,
// }, {
//     imgSrc: 'https://images-na.ssl-images-amazon.com/images/I/51Eyjz65gyL._SX284_BO1,204,203,200_.jpg',
//     title: 'The Diary Of a Young Girl',
//     shortTitle: 'The Diary Of a Young Girl',
//     author: 'Anne Frank',
//     genre: 'Non-Fiction',
//     price: 31.99,
//     discount: 25,
//     isTopSeller: false,
//     isNewArrival: false,
// }]

// addBooks(booksData)

